name: Build Intersect

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  VERSION_PREFIX: 0.7.2
  VERSION_SUFFIX: -beta.

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache binaries
      uses: actions/cache@v3.2.6
      id: cache-binaries
      with:
        path: |
          Intersect*/bin/Release/**/Intersect*
        key: ${{ runner.os }}-nuget-${{ hashFiles('Intersect.*/**/*.cs') }}

    - name: Cache NuGet dependencies
      if: steps.cache-binaries.outputs.cache-hit == 'false'
      uses: actions/cache@v3.2.6
      id: cache-nuget
      with:
        path: |
          ~/.nuget/packages
          Intersect*/obj/project.assets.json
        key: ${{ runner.os }}-nuget-${{ hashFiles('Intersect.*/*.csproj') }}

    - name: Add msbuild to PATH
      if: steps.cache-binaries.outputs.cache-hit == 'false' || steps.cache-nuget.outputs.cache-hit == 'false'
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64

    - name: Setup NuGet.exe for use with actions
      if: steps.cache-binaries.outputs.cache-hit == 'false' || steps.cache-nuget.outputs.cache-hit == 'false'
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@fd9fffd6ca4541cf4152a9565835ca1a88a6eb37
      uses: NuGet/setup-nuget@v1.1.1
      with:
        # NuGet version to install. Can be `latest`, `preview`, a concrete version like `5.3.1`, or a semver range specifier like `5.x`.
        nuget-version: latest # optional, default is latest
        # NuGet API Key to configure.
        # nuget-api-key: # optional
        # Source to scope the NuGet API Key to.
        # nuget-api-key-source: # optional

    # - run: nuget locals all -list

    - name: Restore NuGet Packages
      if: steps.cache-binaries.outputs.cache-hit == 'false' || steps.cache-nuget.outputs.cache-hit == 'false'
      run: nuget restore Intersect.sln

    # - run: ls -R ~/.nuget/packages
    # - run: ls -R

    - name: Build solution
      if: steps.cache-binaries.outputs.cache-hit == 'false' || steps.cache-nuget.outputs.cache-hit == 'false'
      run: msbuild Intersect.sln /p:Configuration=Release /p:PackageVersion=${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}${{ github.run_number }}+build.${{ github.sha }} /p:Version=0.7.2.${{ github.run_number }}

    # - run: ls -R

    - name: Checkout assets main_upgrade branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: assets_upgrade
        repository: AscensionGameDev/Intersect-Assets
        ref: main_upgrade
        token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}

    - name: Checkout target main_full branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: assets_full
        repository: AscensionGameDev/Intersect-Assets
        ref: main_full
        token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}

    - name: Package artifacts
      uses: AscensionGameDev/actions@4c9073d0721da476ac9337fbbfe46a9ca1ae4389
      with:
        bundle: .github/bundles/*.json
        version: ${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}${{ github.run_number }}+build.${{ github.sha }}

    # - name: Package artifacts
    #   run: |
    #     mkdir dist
    #     mkdir intersect-engine
    #     mkdir intersect-engine/client
    #     mkdir intersect-engine/editor
    #     mkdir intersect-engine/server
    #     Copy-Item -Path "Intersect.Client/LICENSE.md" -Destination "intersect-engine/client"
    #     Copy-Item -Path "Intersect.Client/bin/Release/**/Intersect Client.exe*" -Destination "intersect-engine/client"
    #     Copy-Item -Path "Intersect.Client/bin/Release/**/Intersect Client.pdb" -Destination "intersect-engine/client"
    #     Copy-Item -Path "Intersect.Editor/LICENSE.md" -Destination "intersect-engine/editor"
    #     Copy-Item -Path "Intersect.Editor/bin/Release/**/Intersect Editor.exe*" -Destination "intersect-engine/editor"
    #     Copy-Item -Path "Intersect.Editor/bin/Release/**/Intersect Editor.pdb" "intersect-engine/editor"
    #     Copy-Item -Path "Intersect.Server/LICENSE.md" -Destination "intersect-engine/server"
    #     Copy-Item -Path "Intersect.Server/bin/Release/**/Intersect Server.exe*" -Destination "intersect-engine/server"
    #     Copy-Item -Path "Intersect.Server/bin/Release/**/Intersect Server.pdb" -Destination "intersect-engine/server"
    #     Copy-Item -Path "AUTHORS.md" -Destination "intersect-engine"
    #     Copy-Item -Path "LICENSE.md" -Destination "intersect-engine"
    #     Copy-Item -Path "README.md" -Destination "intersect-engine"
    #     Copy-Item -Path "Documentation" -Destination "intersect-engine" -Recurse
    #     Compress-Archive -Path "intersect-engine" -DestinationPath "intersect-${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}${{ github.run_number }}+build.${{ github.sha }}.zip"

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v3.1.2
    #   with:
    #     if-no-files-found: error
    #     name: intersect-${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}${{ github.run_number }}+build.${{ github.sha }}
    #     path: |
    #       AUTHORS.md
    #       Documentation/**
    #       Intersect.*/LICENSE.md
    #       Intersect.Client/bin/Release/**/Intersect Client.*
    #       Intersect.Editor/bin/Release/**/Intersect Editor.*
    #       Intersect.Server/bin/Release/**/Intersect Server.*
    #       LICENSE.md
    #       README.md
    #       !Intersect.*/bin/Release/**/*.xml
    #       !Intersect.*/bin/Release/**/*.runtimeconfig.*
    #     retention-days: 1

    # - name: Download artifacts
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: intersect-${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}${{ github.run_number }}+build.${{ github.sha }}
    #     path: artifacts

    # - run: ls -R

    - name: Publish Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: "dist/*.zip"
        generate_release_notes: true
        prerelease: true
        name: ${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}${{ github.run_number }}
        tag_name: v${{ env.VERSION_PREFIX }}${{ env.VERSION_SUFFIX }}${{ github.run_number }}
        target_commitish: ${{ github.sha }}
